### PR TITLE
[SW-2037] Remove deprecated setClusterConfigFile from H2OConf

### PR DESCRIPTION
**Pull request by mn-mikke**

### CODE REVIEW

**Comment by jakubhava** [comment]
Ah, missed this one, luckily infra captured that. We need to update ExternalH2OBackend.scala with the new configuration

**Comment by mn-mikke** [comment]
@jakubhava I've created separate PR https://github.com/h2oai/sparkling-water/pull/1920 to fix to problem to propagate it also to `rel` branch.

**Comment by jakubhava** [comment]
Ups, one more: There is a python test still using the old method setClusterConfigFile

**Comment by mn-mikke** [comment]
@jakubhava here is the fix https://github.com/h2oai/sparkling-water/pull/1933

**Pull request merged**
