### PR TITLE
[SW-1318] Add back the asDataFrame(.., SQLContext) method to JavaH2OContext

### PR DESCRIPTION
**Pull request by mn-mikke**

### CODE REVIEW

**Comment by mn-mikke** [comment]
What about master?

**Comment by jakubhava** [comment]
**rel-2.4** and **master** introduce the removal of sqlContext about a year ago, so we broke API only on rel-2.1, rel-2.2 and rel-2.3

**Comment by mn-mikke** [comment]
ok, thanks!

**Comment by mn-mikke** [comment]
Merged the PR to rel-2.3, rel-2.2 and rel-2.1 manually

**Pull request closed without merging**
