### PR TITLE
[SW-XXX] Avoid the client to take part of model training

### PR DESCRIPTION
**Pull request by michalkurka**

### CODE REVIEW

**Comment by h2o-ops** [comment]
Hi @michalkurka, your PR title "Avoid the client to take part of model training" is missing JIRA issue number! Please specify it in the following form [SW-]

**Comment by michalkurka** [comment]
Still work-in-progress

**Comment by jakubhava** [comment]
@michalkurka can I close this PR?

**Comment by michalkurka** [comment]
@jakubhava I am planning to finish it

**Comment by jakubhava** [comment]
Ok, can you please create a JIRA?

Also you probably need to update your code as we switched master branch today

**Comment by jakubhava** [comment]
@michalkurka I will close this PR to avoid stalled PRs, please feel free to re-open any time you continue working on it. Thanks!

**Pull request closed without merging**
