### PR TITLE
[SW-265] Use Spark Session in public API instead of Spark Context

### PR DESCRIPTION
**Pull request by jakubhava**
<s>TODO: Documentation changes<s>

### CODE REVIEW

**Comment by mmalohlava** [comment]
Also the tests are failing now:

```
org.apache.spark.h2o.H2OConfTestSuite > test H2OConf parameters FAILED
    java.lang.NoSuchMethodException at H2OConfTestSuite.scala:29```

**Comment by jakubhava** [comment]
@mmalohlava Yup, I saw the failure but had to leave for train. Working on it now 👍

**Comment by jakubhava** [comment]
Should be passing now, waiting for tests to finish

**Comment by mmalohlava** [comment]
Thinking about it little bit more:
  - where is boundary between using `SparkContext` and `SparkSession`?

Would it make sense to have part of SW which depends on SparkContext only?

**Comment by jakubhava** [comment]
Since SparkSession is wrapping also `sqlContext` I was thinking of removing implicit `SQLContext` argument to `AsDataFrame` methods wince spark session contains it. 

Regarding the boundary - I think that on `H2OContext` and REPL level we should use SparkSession since it has the sqlContext and sparkContext and we could apply the simplification above. However the rest of the code can use SparkContext as we do now.

Since this would be API change it's good to discuss this properly, thanks for new ideas @mmalohlava !

**Comment by mmalohlava** [comment]
One more comment - this is changing API, so all people using SparkContext will need to rewrite code. Is it possible to preserve the old API as well, and we will remove it in 3.x?

**Comment by jakubhava** [comment]
@mmalohlava good point. I think I already implemented that - both `sparkContext` and `sparkSession` are accepted but deprecation warning is printed in case of `sparkContext`

**Pull request merged**
