### PR TITLE
[SW-XXX] programmer error:  " is lost

### PR DESCRIPTION
**Pull request by ningbogao**
programmer error:  " is lost

### CODE REVIEW

**Comment by h2o-ops** [comment]
Hi @ningbogao, your PR title "programmer error:  " is lost" is missing JIRA issue number! Please specify it in the following form [SW-]

**Comment by ningbogao** [comment]
<if not exist "%FAT_JAR_FILE%"  > for this commond  the end of "" is lost!

**Comment by ningbogao** [comment]
programmer error: " is lost to [SW-#685]

**Comment by jakubhava** [comment]
Thanks @ningbogao for the fix! Merging

**Pull request merged**
