### PR TITLE
[GH-5676][GH-5679][GH-5619] Add support for Python 3.10 & 3.11

### LINKED ISSUE #5619: Support for Python 3.10 in H2O Packages
The following H2O packages are currently unavailable for Python 3.10 in client's Artifactory:

h2o
h2o_pysparkling_3.0
h2o_pysparkling_scoring_3.0

For more context, support ticket#: 105447
Jira: https://h2oai.atlassian.net/browse/SW-2786

### LINKED ISSUE #5676: Add support for Python 3.10

### LINKED ISSUE #5679: Add support for Python 3.11

### PR DESCRIPTION
**Pull request by krasinski**
closes #5676 closes #5679 closes #5619

### CODE REVIEW

**Review by tomasfryda — APPROVED** [review]
LGTM! Thank you @krasinski !

**Comment by mn-mikke** [comment]
@krasinski Can you also add support for python 3.11 in this PR? It will save you one image build. I think you will need to ignore tests for python 3.10.

**Comment by tomasfryda** [comment]
@mn-mikke python 3.12 is already out (https://docs.python.org/3/whatsnew/3.12.html). Would it make sense to include it here as well?

**Comment by mn-mikke** [comment]
@tomasfryda We would need to add the support for 3.12 in h2o first. Also there is no pyspark version that would support 3.12. This is the latest: https://pypi.org/project/pyspark/

**Comment by mn-mikke** [comment]
Only spark 3.4 supports python 3.11:
https://issues.apache.org/jira/browse/SPARK-41454
https://pypi.org/project/pyspark/3.3.3/
https://pypi.org/project/pyspark/3.4.0/

**Review by mn-mikke — APPROVED** [review]
LGTM, thank you!

**Pull request merged**
