### PR TITLE
[SW-639] Use persist layer for exportPOJOModel

### PR DESCRIPTION
**Pull request by miuma2**

### CODE REVIEW

**Comment by h2o-ops** [comment]
Hi @miuma2, your PR title " use persist layer for exportPOJOModel" is missing JIRA issue number! Please specify it in the following form [SW-]

**Comment by jakubhava** [comment]
Thanks @miuma2 !

**Comment by jakubhava** [comment]
@miuma2 can you please rebase the change on top of the master branch to resolve the rebase conflicts ?

**Comment by miuma2** [comment]
@jakubhava, if I try to rebase it says that my forked repo is up to date. I also don't see any conflicts. I could reset my repo and apply on top the new changes if that's helping. Thanks for your advice.

**Comment by jakubhava** [comment]
No problem, I managed to merge it. Thanks @miuma2 !

**Pull request merged**
