### PR TITLE
[SW-2409] GLRM has label col even though it is unsupervised algorithm

### PR DESCRIPTION
**Pull request by jakubhava**

### CODE REVIEW

**Comment by mn-mikke** [comment]
It seems that the project doesn't need any CI if the PR's are being straintly merged...

**Comment by jakubhava** [comment]
Let's be direct -> it was me who merged the PR. I merged the PR directly as I wanted to build on top of it and the PR is rather simpler. I try to wait until the CI is done in more complex PRs

**Comment by mn-mikke** [comment]
Yeah, you're the only person working on the project... It won't cause conflicts in PRs of other people.

**Comment by jakubhava** [comment]
I'm sorry, it won't happen again.

**Pull request merged**
