### PR TITLE
[SW-2413] Upgrade MOJO Runtime to 2.4.8

### PR DESCRIPTION
**Pull request by mn-mikke**

### CODE REVIEW

**Review by jakubhava — APPROVED** [review]
LGTM from the code point of view. Not sure if mojo hasn't changed other APIs as well

**Comment by mn-mikke** [comment]
>  Not sure if mojo hasn't changed other APIs as well
@jakubhava What do you mean by other APIs?

**Comment by jakubhava** [comment]
Just mojo API -> what I meant is that if it complies, we are probably fine...

**Comment by mn-mikke** [comment]
I see. I want to check it with @mmalohlava or @pkozelka that the upgrade won't break anything.

**Review by pkozelka — APPROVED** [review]

**Pull request merged**
