### PR TITLE
[SW-1958] Property for Passing Extra Jars to External Backend

### PR DESCRIPTION
**Pull request by mn-mikke**

### CODE REVIEW

**Comment by jakubhava** [comment]
Ah I see, it is used in the benchmarks, is it necessary though?

**Comment by mn-mikke** [comment]
Yes, the motivation is coming from benchmarks https://github.com/h2oai/sparkling-water/pull/1844#issuecomment-587420137 . IMHO, this property might be helpful in future anyway. WDYT?

**Comment by jakubhava** [comment]
Yup, I would keep it exposed, just wanted to ask for the motivation in case of benchmarks :) Thanks!

**Comment by jakubhava** [comment]
Thank you @mn-mikke!

**Pull request merged**
