### PR TITLE
[SW-XXX] Parallel jenkins build steps 

### PR DESCRIPTION
**Pull request by nikhilshekhar**

### CODE REVIEW

**Comment by h2o-ops** [comment]
Hi @nikhilshekhar, your PR title is missing JIRA issue number!

**Comment by h2o-ops** [comment]
Hi @nikhilshekhar, your PR title is missing JIRA issue number!

**Comment by h2o-ops** [comment]
Hi @nikhilshekhar, your PR title is missing JIRA issue number!

**Comment by h2o-ops** [comment]
Hi @nikhilshekhar, your PR title is missing JIRA issue number!

**Comment by h2o-ops** [comment]
Hi @nikhilshekhar, your PR title is missing JIRA issue number!

**Comment by h2o-ops** [comment]
Hi @nikhilshekhar, your PR title is missing JIRA issue number!

**Comment by jakubhava** [comment]
Hi @nikhilshekhar,
 even though this is a constant work in progress, could you plese create a JIRA for the work you're doing so we have JIRA numbers for everything and also add this JIRA number to the PR itself so the PR starts with the [SW-NUMBER] prefix ? Thanks!

Then after you're done with all the work you can squash it to one or few more commits which should in format `[SW-NUMBER] Explanation`

**Comment by h2o-ops** [comment]
Hi @nikhilshekhar, your PR title is missing JIRA issue number!

**Comment by h2o-ops** [comment]
Hi @nikhilshekhar, your PR title is missing JIRA issue number!

**Comment by jakubhava** [comment]
@nikhilshekhar could you please create a new JIRA for this issue and rename the PR and the commit to the prefix with corresponding jira version ?  [SW-380] was to introduce JenkinsFile which is already done and I marked that as resolved. Making it parallel can be separated into a new Jira.

**Comment by jakubhava** [comment]
Or maybe you can first check with @mmalohlava if https://github.com/h2oai/sparkling-water/pull/276 doesn't collide with this ( maybe one can already be closed ). Thanks!

**Comment by mmalohlava** [comment]
I would close this PR for now.

**Pull request closed without merging**
