### PR TITLE
[SW-2457] Fix Deployment of Kubernetes Tests on Jenkins

### PR DESCRIPTION
**Pull request by mn-mikke**

### CODE REVIEW

**Comment by Pscheidl** [comment]
@mn-mikke Mark as draft for now ?

**Comment by mn-mikke** [comment]
@Pscheidl This PR should fix deployment of EKS. The fixes for individual tests will come in different PRs if you agree.

**Review by Pscheidl — APPROVED** [review]

**Comment by Pscheidl** [comment]
If you're fine with failing tests everywhere "based on master", then I'm fine with that too. Those were not running anyway.

**Comment by mn-mikke** [comment]
> If you're fine with failing tests everywhere "based on master", then I'm fine with that too.

They have been failing anyway.

**Pull request merged**
