### PR TITLE
[PRE-RELEASE] 1.6 branch update

### PR DESCRIPTION
**Pull request by mdymczyk**
Cherry picks stuff from master to the 1.6 branch.

### CODE REVIEW

**Comment by mdymczyk** [comment]
The tests are passing but I haven't really tested this branch yet myself.

**Comment by jakubhava** [comment]
@mdymczyk how urgent is review of this PR pls ?

**Comment by mdymczyk** [comment]
@jakubhava asap I'd say since we haven't updated the 1.6 branch in quite a while I think? But I'd leave the final say to @mmalohlava

**Comment by jakubhava** [comment]
oki oki, I have some important tasks to do at the moment but will try to allocate some time for review of this branch as soon as possible as well

**Comment by jakubhava** [comment]
But we need to test it also at runtime to be sure REPL works in all cases

**Comment by mmalohlava** [comment]
Most of people asking for 1.6 moved already to 2.x - but still it is nice to have.

**Comment by jakubhava** [comment]
@mdymczyk I'm doing the review just right now. If I understand correctly, we cherry-picked also the cross-compulation support stuff which means that this branch needs to be tested against both scala 2.10 and 2.11.

**Comment by jakubhava** [comment]
I'll finish the regular review and then I will try to do the fixes myself so I can test it on a new version immediately, hope that's ok

**Comment by jakubhava** [comment]
So so far https://0xdata.atlassian.net/browse/SW-189 not fixed by this, but as we talked with @mmalohlava, we'll leave this into next h2o iteration

**Comment by jakubhava** [comment]
@mdymczyk @mmalohlava This branch is passing tests in jenkins on spark 1.6 compiled with Scala 2.10.

What I can do right not is to 
1) merge right away
2) spend some time and create a new jenkins job which would compile spark 1.6 with scala 2.11 and test it on there

**Comment by jakubhava** [comment]
went with the 2). Will remove the temporary Jenkins job afterwards, once it's tested I will merge

**Comment by jakubhava** [comment]
@mdymczyk @mmalohlava From my side, good to merge.

**Comment by jakubhava** [comment]
As we talked, I'm merging this change. Keeping the commits un-squashed since it's a big change

**Pull request merged**
