### PR TITLE
AB_SW-183

### PR DESCRIPTION
**Pull request by angela0xdata**
Initial version of Sparkling Water help system based on master branch. Run `make html` to build the system locally and view the output. Several topics were rewritten (specifically the main README). If this is approved, then I can apply similar updates to other release branches and then provide pointers on the h2o.ai/docs page to each version rather than just the master readme in github.

### CODE REVIEW

**Comment by jakubhava** [comment]
@angela0xdata Sorry for holding this PR that long. Can you please rebase this branch on current master and do corresponding changes to the newly added documentation ? Thanks!

**Comment by mmalohlava** [comment]
We will need to do manual merge/rebase - i do not want to change the updated information which we introduced in SW2.0 changes.  Rebase will not help, since it will lead into annoying conflicts in text ...

**Comment by mmalohlava** [comment]
Can we update this PR to match current state of docs?

**Comment by jakubhava** [comment]
@angela0xdata could you please have a look on sparkling-water doc again, maybe update it on current master ? There has been a lot changes since this branch has been created.

**Comment by angela0xdata** [comment]
Deleting this branch. Will update with newer version.

**Pull request closed without merging**
