### PR TITLE
[SW-2560] Expose all H2OMOJOModels from AutoML Leaderboard

### PR DESCRIPTION
**Pull request by mn-mikke**

### CODE REVIEW

**Review by michalkurka — APPROVED** [review]
I think the PR looks good.

It made me realize that the AutoML models are not deleted from DKV after the training is finished - can this create a memory leak?

**Review by sebhrusen — APPROVED** [review]
This looks good!

**Comment by sebhrusen** [comment]
> It made me realize that the AutoML models are not deleted from DKV after the training is finished - can this create a memory leak?

@michalkurka if SW is only using the Mojos after training, then I agree with you that it could, should even, delete the AutoML instance from DKV, which will remove the attached models alltogether.

**Comment by mn-mikke** [comment]
Binary models are not deleted even after fitting of a standalone SW algorithm. Let's improve this in another PR https://h2oai.atlassian.net/browse/SW-2566.

**Pull request merged**
