### PR TITLE
[SW-276] Fix classloading problem of classes not defined in repl when…

### PR DESCRIPTION
**Pull request by jakubhava**
… repl is enabled

Explanation is here https://0xdata.atlassian.net/browse/SW-276

### CODE REVIEW

**Comment by mmalohlava** [comment]
Need to be tested on Databricks and Azure environments.

**Comment by mmalohlava** [comment]
And with Hive.

**Comment by mmalohlava** [comment]
Sorry, i accidentally closed the PR.

**Comment by jakubhava** [comment]
Yup, I'm now running yarn and script tests in jenkins. Already tested in DBC and fix works as expected

**Comment by mmalohlava** [comment]
We need more automatic tests for that - DBC, Azure. No manual testing...it is too error prone.

**Comment by jakubhava** [comment]
@mmalohlava agree!

**Pull request merged**
