### PR TITLE
[SW-XXX] Another pipeline experiments.

### PR DESCRIPTION
**Pull request by mmalohlava**

### CODE REVIEW

**Comment by h2o-ops** [comment]
Hi @mmalohlava, your PR title "Another pipeline experiments." is missing JIRA issue number! Please specify it in the following form [SW-]

**Comment by h2o-ops** [comment]
Hi @mmalohlava, your PR title "Another pipeline experiments." is missing JIRA issue number! Please specify it in the following form [SW-]

**Comment by jakubhava** [comment]
@mmalohlava what is the state of this PR please ? Just want to avoid stalled PRs 👍

**Comment by mmalohlava** [comment]
This is active pr.

**Pull request closed without merging**
