### PR TITLE
[SW-1710] Update external backend docs for "allow client"

### PR DESCRIPTION
**Pull request by michalkurka**

### CODE REVIEW

**Comment by h2o-ops** [comment]
Hi @michalkurka, your PR title "Update external backend docs for "allow client"" is missing JIRA issue number! Please specify it in the following form [SW-]

**Comment by jakubhava** [comment]
@michalkurka We already have PR for this -> I will update https://github.com/h2oai/sparkling-water/pull/1620 based on the missing pieces

**Comment by michalkurka** [comment]
@jakubhava ok, thank you

**Comment by michalkurka** [comment]
@jakubhava I was also going to add something like this to the migration document:


To 3.26.11
-----------------

External cluster needs to be started with a new option
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

- Users of Sparkling Water external cluster on Hadoop need to update the command the external cluster is lauched with.
  A new parameter `-sw_ext_backend` needs to be added to the h2odriver invocation.

**Comment by jakubhava** [comment]
oki, done, please check the original PR

**Pull request closed without merging**
