### PR TITLE
[SW-165] Fixes CSS for Scala cell to black

### PR DESCRIPTION
**Pull request by mdymczyk**

### CODE REVIEW

**Comment by MadMan0708** [comment]
Cool! 

The best would be to put this change straight into h2o-flow - https://github.com/h2oai/h2o-flow/blob/master/src/scala-editor.styl

**Comment by mmalohlava** [comment]
It is Sparkling Water specific style - flow dev iteration is too long since it depends on also releasing H2O (tiny change in style would trigger release of Flow followed by release of H2O - in our 3 week release cycle it is simply slow). 

Better to have in our project where we can iterate much more easily.

But at the end it should go eventually to flow

**Comment by MadMan0708** [comment]
ok, make sense, never mind than

**Comment by mmalohlava** [comment]
Lets look at style, improve it little bit, then propagate to Flow.

**Pull request merged**
