### PR TITLE
[SW-466] Separate DEVEL.md into multiple doc files

### PR DESCRIPTION
**Pull request by jakubhava**
- convert to rst
- make up-to-date with current spark
- also make up-to-date with 2 backends types

### CODE REVIEW

**Comment by jakubhava** [comment]
Already done. All docs made up-to-date, converted to rst and separated. Should be a good step for the next documentation steps.

**Comment by mmalohlava** [comment]
Great! One minor thing - can we put into `doc` folder one file as entry point (probably it will look like `DEVEL.md`, but we can design a new one.)

**Comment by jakubhava** [comment]
I think it's already there. There is DEVEL.rst inside the doc folder which acts as the table of content.

**Comment by mmalohlava** [comment]
Great! SO i think we can merge! 🎉

**Pull request merged**
