### PR TITLE
[SW-652] - Documentation as HTML output for master branch

### PR DESCRIPTION
**Pull request by angela0xdata**
- Added required Sphinx style, config, make, and image files
- Reviewed and edited content
- gitignore will ignore all outputted build files

### CODE REVIEW

**Comment by mmalohlava** [comment]
@angela0xdata thanks a lot! this is great! Let me pls know when this is ready, i would like to make a few additional changes.

@jakubhava pls do not merge it yet

**Comment by angela0xdata** [comment]
You can run `make html` in the /doc folder to view how this looks and how it's organized. The version number is configured the same way as h2o-3 (specified in the conf.py file), so I'm not sure if that is the same process as Sparkling Water.

**Comment by jakubhava** [comment]
Thanks a lot @angela0xdata! Let me know if I can help on this in any way.

@mmalohlava no worries, we can merge when this is completely done

**Comment by jakubhava** [comment]
@mmalohlava @angela0xdata few ideas -> it might be good to parametrise all the versions and fix that change and put it into a single file where we can configure all of it, such as sparkling water version, scala version and so on. This could eliminate human error.

We have also README.rst for pysparkling in here -> https://github.com/h2oai/sparkling-water/blob/master/py/README.rst. Maybe we could make it part of the docs as well

**Comment by mmalohlava** [comment]
@jakubhava yup, we also need to have an artifact from this and deploy it, and have kind of uber SW documentation for all versions.

**Comment by mmalohlava** [comment]
Proposed changes (@jakubhava pls comment):
  - use https://github.com/trustin/sphinx-gradle-plugin to keep build in gradle land
  - move code under `src/site/sphinx` (will break existing links :/)
  - build a distribution jar file which contains built site but also source code of the site (i am still not sure how to integrate packages in upstream project - let's say project composing documentations from all projects)

WDYT?

**Comment by jakubhava** [comment]
Absolutely agree with gradle build plugin, everything in sw should be buildable using Gradle. Also agree with putting source code into doc/src

If you agree @angela, I can have a look on the gradle plugin tomorrow after I release

Kuba

**Comment by angela0xdata** [comment]
I don't have any objections. (Mostly because I don't understand the gradle plugin.) I do worry a bit about having broken links, though.

**Comment by jakubhava** [comment]
Also what would be good to do:
 - in the master branch doc, reference to just the latest sparkling water. Let documentation for each rel 2.2, 2.1 and 2.0 talk about their versions

**Comment by jakubhava** [comment]
@angela0xdata @mmalohlava I did several improvements to this branch today:
- bring on top of master and resolve conflicts
 - use gradle plugin. The documentation can now be build as : ./gradlew
 site
 - move rst files to the source directory together with the sphinx files
 - make copy of CHANGLOG.rst in source dir ( using include directive )
 so we can keep the original CHANGELOG in the current location as well
- the sparkling-water and h2o versions are automatically generated
- the version is added to the project

**Comment by jakubhava** [comment]
Should be again on top of master :)

**Comment by jakubhava** [comment]
Jar file is now generated out of the generated sphinx documentation page

**Comment by angela0xdata** [comment]
Can someone review/approve so that I can merge this while it works :) ... Also, I'm still showing a conflict with /doc/tutorials/extending_h2o_jar_manually.rst (which should be deleted).

**Comment by jakubhava** [comment]
@angela0xdata if you don't mind I will merge it my morning. I would like to fix the bug with the jar preparation and make it ready for publication as part of this PR.

**Comment by jakubhava** [comment]
Merged. I also cherry-picked and made corresponding changes on the releases branches so it's on master, rel-2.2, rel-2.1 and rel-2.0

**Pull request merged**
