### PR TITLE
[SW-512] Make JenkinsFile up-to-date with sparkling_yarn_branch

### PR DESCRIPTION
**Pull request by jakubhava**

### CODE REVIEW

**Comment by jakubhava** [comment]
As of this point, this change is more up-to-date version of https://github.com/h2oai/sparkling-water/pull/320 ( Sorry for JIRAs duplication, the initial goal was a bit different )

**Comment by mmalohlava** [comment]
Does it include: https://github.com/h2oai/sparkling-water/pull/320/files ?

**Comment by jakubhava** [comment]
Yup -> Except the `linux` label as the environment is not consistent across nodes at the moment

**Comment by mmalohlava** [comment]
yup, that's fine - i am using it as a proxy to show that we have messy environment. 

Nevertheless, i would prefer to dockerize all steps. We have also internal docker registry - so we can even use it.

**Comment by mmalohlava** [comment]
But good change, if you think that my PR is not needed anymore, pls, close it

**Comment by jakubhava** [comment]
Cool, didn't know about the internal docker hub! If you like, we can merge this whenever you want. Or feel free to update it :)

**Comment by jakubhava** [comment]
All Jenkins job can be removed at this point in favor of this pipeline

**Pull request merged**
