### PR TITLE
Fixed spark version extraction

### PR DESCRIPTION
**Pull request by vpatryshev**
Taking care of NPE and IOOBE.

### CODE REVIEW

**Comment by jakubhava** [comment]
I'm not sure if this is necessary since we always put `spark.version` file into the resources. The case where it's missing should never happen. If we decide to check it anyway, I would rather check assembly jar whether it contains the file or not as part of gradle build ( because if it's missing that means something went wrong with the build )

**Comment by vpatryshev** [comment]
Jakub, if it does not happen, we can as well throw an exception explaining in details what's wrong. Why make developers life hard? Do you like it? I talked with Michal, he agreed that we should return some text. Are you going to check assembly jars all around the world? Or? What exactly is your suggestion? I'll gladly implement it. But please let not keep uses in the dark regarding the problems, ok? Just share your idea, and let's make sure Michal has the same opinion. I personally don't care either way. I don't want to throw obscure exceptions, that's it. Do you like obscure exceptions? What's their purpose?

**Comment by mmalohlava** [comment]
Checking on both sides makes good sense:
  - at build time to produce correct artifacts
  - at runtime since people can bundle sparkling-water-core into FatJar and have different fat jarring process with different filters (e.g., skipping `spark.properties` for some reason).

Thinking about it more - probably we should have an option to disable the compatibility check..

**Comment by vpatryshev** [comment]
Disabling compatibility check is not in the scope of this small change. I have no opinion, probably Michal knows better whether it makes sense. Or we could return and Option[String].

What's exactly your suggestion regarding the current code?

**Comment by jakubhava** [comment]
@vpatryshev I understand your point of view, but your message feels like filled with emotions instead of explanation why and why not it's bad or good. I'm always opened to other ideas, the fact I wrote the first comment doesn't mean I will end up liking it et the end after ideas of others, I like to collaborate. Also I can't know what people discussed in the office and what not, since I'm remote.

**Comment by vpatryshev** [comment]
Jakub, sure, we may have talked about something, but it was not reflected anywhere.

So, what happened. I updated SPARK on my machine yesterday, built an app with gradlew, and it started throwing this error. Of course the cause is somewhere outside. But we should report it properly, not keep it enigmatic. I guessed the cheapest solution (I'm not its fan, but well, I'm trying to be soft) was to provide some human-readable text. I would prefer throwing an exception instead. So if you agree with me, I'll replace returning that nice text (which hardly anybody will read, for obvious reason) with an exception. But please come up with some suggestion, if you don't feel this current solution is good. :)

**Comment by jakubhava** [comment]
@vpatryshev thanks for explanation! 

I think this solution is fine. It makes sense that we should check it at build and runtime as @mmalohlava pointed out. 

I'm not sure whether to choose the message or the exception. From my point of view an exception should be thrown - but on the other hand - no code doesn't depend on the spark version directly so I can imagine that at some points, the exception would be too much and text makes sense. If you decided to go with the text with @mmalohlava we can keep it like that.

**Comment by vpatryshev** [comment]
Let's ask Michal:

Michal, do you mind if I throw an exception instead?

**Comment by mmalohlava** [comment]
+1 for exception - we need to make sure that users running SW on right version of Spark. When we can see wrong version or no version => throw exception.

Later we should introduce an option to override this.

**Comment by vpatryshev** [comment]
Thank you all; now an exception is thrown!

**Comment by jakubhava** [comment]
@vpatryshev Could you please squash the commits, create JIRA for it, put the JIRA number - [SW_NUMBER] - to commit as prefix to the message and rebase on top of current master ? Then we can merge 👍

**Comment by vpatryshev** [comment]
OK, sure.

Thanks,
-Vlad

**Pull request merged**
