### PR TITLE
[SW-2091] Import Hive table over rest

### PR DESCRIPTION
**Pull request by jakubhava**

### CODE REVIEW

**Comment by jakubhava** [comment]
I might be a bit lost, I thought I have updated the hive docs in this PR, am I missing something?

**Comment by mn-mikke** [comment]
I'm just asking whether the section for kerberberized cluster shoul'd use SW API instead of H2O API.

**Comment by jakubhava** [comment]
Ah, yes that is a good point. The links were pointing to the methods in Py/Scala so I was confused what doc did you mean. I will update the kerberos part

**Comment by jakubhava** [comment]
@mn-mikke should be better now, please have a look

**Pull request merged**
