### PR TITLE
[SW-1975] Move spark.ext.h2o.hdfs_conf Property among Properties of Internal Backend

### PR DESCRIPTION
**Pull request by mn-mikke**
I propose to move this property since it's used only by the internal backend.

### CODE REVIEW

**Comment by jakubhava** [comment]
I think we should still keep it exposes as it is as people in external backend might want to point to specific HDFS configuration manually, WDYT?

**Comment by mn-mikke** [comment]
@jakubhava I thought that the outcome of your discussion with @michalk was that this property will be supported only for the internal backend? Has anything changed?

**Comment by mn-mikke** [comment]
I'm happy with any solution, but current situation seems to me inconsistent.

**Comment by jakubhava** [comment]
Yup, agree, I just confused myself :) Feel free to merge, thank you!

**Pull request merged**
