### PR TITLE
[SW-593] H2OConf initialization exception on windows

### PR DESCRIPTION
**Pull request by RobinTPotter**
change to file:/// to initialize the H2OConf. /// is understood by all according to https://en.wikipedia.org/wiki/File_URI_scheme (including windows shell)

### CODE REVIEW

**Comment by h2o-ops** [comment]
Hi @RobinTPotter, your PR title "Update initializer.py" is missing JIRA issue number! Please specify it in the following form [SW-]

**Comment by RobinTPotter** [comment]
hi @h2o-ops - I wouldn't know a JIRA number if it gave me a haircut :)

**Comment by RobinTPotter** [comment]
updated

**Comment by jakubhava** [comment]
Great, thanks a lot! I just did some testing on my Unix machine and it works as well. Let just wait for the tests to finish and then we can merge 👍

**Comment by jakubhava** [comment]
On unix the created path will be actually `file:////xx/yy` because of the prepended `file:///` and the absolute path `/xx/yy`. I tried it and worked fine on Mac and out test machines, however seems like this is not standardised.

What we can do yo avoid this is to check if `sw_jar_file` starts with `/` and if it doesn't, we can add it. What do you think @RobinTPotter ? can you please change it ?

**Comment by jakubhava** [comment]
Perfect, looks good! Thanks for contribution!

**Comment by RobinTPotter** [comment]
thanks, added a check

**Pull request merged**
