### PR TITLE
Update and rename README.rst to README.md

### PR DESCRIPTION
**Pull request by Mistobaan**
WIP trying to change the format from rst to md and updating the versions. Here just for early comments

### CODE REVIEW

**Comment by angela0xdata** [comment]
The reason for .rst is so that it is compatible with Sphinx-built documentation. The eventual output for Sparkling Water documentation is an html user guide similar to the Steam and H2O user guides. Our Sphinx theme doesn't support md, so we're switched to rst. Users who view the readme files on github will have no negative experience with reading rst vs md.

**Comment by Mistobaan** [comment]
Seems you can use markdown files now in sphinx:

- http://stackoverflow.com/questions/2471804/using-sphinx-with-markdown-instead-of-rst

**Comment by angela0xdata** [comment]
That's correct, but md does not work with the sphinx template that we use.

**Comment by jakubhava** [comment]
@angela0xdata so md is not supported in our documentation ? In that case can you @Mistobaan change this PR to just contain documentation fixes ( without converting it to md ) ?  Also can you pls create a JIRA for it in sparkling-water and put the jira number as part of the commit message as [SW-JIRA_NUM] Update Python documentation?

**Comment by jakubhava** [comment]
Closing this PR since it's completely out of date

**Pull request closed without merging**
