### PR TITLE
[SW-355] Put latest rsparkling into the distribution package

### PR DESCRIPTION
**Pull request by jakubhava**
Also remove dead code in `./make-dist` script

### CODE REVIEW

**Comment by mmalohlava** [comment]
This needs update of download page to promote a new package.

**Comment by jakubhava** [comment]
Do you mean instructions on how to install package from the distribution zip ? We already have RSparkling tab so we can put the instructions there.

I would put there 2 kind of information - install from cran ( the simplest one) and install from distribution jar locally.

What do you think ?

**Comment by mmalohlava** [comment]
Yes pls

**Comment by jakubhava** [comment]
@mmalohlava the download page is updated. Looks as:

screen shot 2017-07-14 at 11 06 24

**Pull request merged**
