### PR TITLE
[SW-380] Minor test changes

### PR DESCRIPTION
**Pull request by mmalohlava**

### CODE REVIEW

**Comment by h2o-ops** [comment]
Hi @mmalohlava, your PR title "Minor test changes" is missing JIRA issue number! Please specify it in the following form [SW-]

**Comment by jakubhava** [comment]
@mmalohlava what is the state of this PR please ?

**Comment by jakubhava** [comment]
@mmalohlava is it ok if I close this PR in favour of https://github.com/h2oai/sparkling-water/pull/360 ? I made my PR up-to-date with Jenkins sparkling-yarn-job plus added some fixes from your branch to have one up-to-date PR

**Comment by mmalohlava** [comment]
👍

**Pull request closed without merging**
