### PR TITLE
[SW-2537] Add support for Spark 3.1

### PR DESCRIPTION
**Pull request by mn-mikke**

### CODE REVIEW

**Comment by h2o-ops** [comment]
Hi @mn-mikke, your PR title "Add support for Spark 3.1" is missing JIRA issue number! Please specify it in the following form [SW-]

**Review by satai — APPROVED** [review]

**Comment by mn-mikke** [comment]
Thanks @satai for you review!

**Comment by derSascha** [comment]
@mn-mikke Do you know if there are any plans to release H2O `3.32.1.2-1` soon?

We need to integrate H2O with a version that supports Spark 3.0 and 3.1. Right now we like to add Spark 3.0 support and add 3.1 later, without upgrading H2O again.

**Comment by mn-mikke** [comment]
@derSascha The current plan is to release SW `3.32.1.2-1` at the beginning of the next week.

**Pull request merged**
