### PR TITLE
[SW-1708] Simplify distribution of security files

### PR DESCRIPTION
**Pull request by jakubhava**
This proposal introduce a small cleanup. I thing we can keep one code path for all the cases using this solution.

What do you think? I have missed this during the review.

Maybe there is a reason for doing it like now, I just not see it :)

### CODE REVIEW

**Comment by mn-mikke** [comment]
@jakubhava I think this is a great improvement! It seems I got lost in various scenarios. In that case I think you can remove the third parameter from property specification. E.g: https://github.com/h2oai/sparkling-water/pull/1614/files#diff-ed060ffa1e96e1fe4dc30499d7cc9a54L263

**Comment by jakubhava** [comment]
Thanks @mn-mikke! I started playing with SSL communication and got this idea.

**Comment by mn-mikke** [comment]
Sorry, I should have mentioned that after the third item from the property spec. The return time of [this](https://github.com/h2oai/sparkling-water/pull/1614/commits/4b4eeca0365509fb1728f3776893182e7ddba1e1#diff-ed060ffa1e96e1fe4dc30499d7cc9a54L204) needs to be modified.

**Comment by jakubhava** [comment]
Ah, good catch, let me fix it

**Comment by jakubhava** [comment]
Fixed, sorry, my bad

**Pull request merged**
