### PR TITLE
[SW-964] Azure Templates

### PR DESCRIPTION
**Pull request by JHerna17**
The only file that needs to be modified on each release is the head_node_installv2.sh with the appropriate minor versions for Spark 2.1, 2.2 and 2.3 (placeholder for now) 

Then it needs to be uploaded to our azure blob storage 
On Azure Government Cloud the access to s3 and github is restricted, hence the need to have these files on blob storage

### CODE REVIEW

**Comment by jakubhava** [comment]
@JHerna17 finally having a look today

**Comment by JHerna17** [comment]
I will verify with HDI 2.3 before Monday

**Comment by jakubhava** [comment]
thank you @JHerna17!

**Comment by jakubhava** [comment]
Hi @JHerna17, I would like to go ahead and merge this. Can you please have a look and let me know if this is the final state? Thanks!

**Comment by jakubhava** [comment]
Closing for now. We should get back to it

**Pull request closed without merging**
