### PR TITLE
[SW-716] H2O KMeans to Spark Pipeline

### PR DESCRIPTION
**Pull request by spaszek**
WIP

### CODE REVIEW

**Comment by jakubhava** [comment]
Thanks @spaszek for this contribution!!

I will try to have a look sonner but in the worst case, I will do proper review at the start of the next week.

But so far, thank you for the great work! In the meanwhile, could you please rebase this branch on top of the current master? Thanks!

**Comment by spaszek** [comment]
@jakubhava - I will mention you once the PR is ready to CR. :)

**Comment by jakubhava** [comment]
Hi @spaszek, how it's going, can I help in any way?

**Comment by jakubhava** [comment]
@spaszek I will close this PR for now, feel free to re-open it when you start working on it again

**Pull request closed without merging**
