### PR TITLE
It's all just a restauration of a pr SW-58

### PR DESCRIPTION
**Pull request by vpatryshev**

### CODE REVIEW

**Comment by jakubhava** [comment]
Thanks @vpatryshev for the new PR, will review as soon as possible. I guess that the original PR https://github.com/h2oai/sparkling-water/pull/180 can be closed now ?

**Comment by jakubhava** [comment]
Just had a brief look - it doesn't seem to bring support for specifying the schema as part of `h2oContext.asDataFrame` method as mentioned in the https://0xdata.atlassian.net/browse/SW-58

Also the file https://github.com/h2oai/sparkling-water/pull/208/files#diff-178b73206c7a06e0fc6a7a43a5302e24 seems to copy of https://github.com/h2oai/sparkling-water/blob/master/core/src/test/scala/org/apache/spark/h2o/DataSourceTestSuite.scala with just additional changes. It seems that these changes can actually be merged into the original one.

**Comment by vpatryshev** [comment]
@jakubhava , so you think just suggesting using sqlContext is not enough? Ok, I'll kick in some more stuff. Will need to pass the schema anyway.

**Comment by jakubhava** [comment]
Cool!But it's not urgent, I just wanted to know what's the state on this branch

**Comment by mmalohlava** [comment]
No actual change, closing for now.

**Pull request closed without merging**
