### PR TITLE
[SW-376] Fix DataType conversion. The DateType is internally handled …

### PR DESCRIPTION
**Pull request by jakubhava**
…as Long and the corresponsing Java class has to be marked as Long as well

### CODE REVIEW

**Comment by mmalohlava** [comment]
Ups, lot of test errors.

**Comment by jakubhava** [comment]
Yup, I haven't pushed a fixed version yet, I have it in my local repo and will push it later tonight

**Comment by jakubhava** [comment]
This is the working fix. We need to explicitly overrides the internal java class which is used during the conversion for these 2 types in external cluster mode.

**Comment by jakubhava** [comment]
still need one small fix on the external backend

**Comment by jakubhava** [comment]
The DeepLearning failing on the external cluster is intermittent issue which happens pretty often, however not related to this change. We can merge and proceed with the release ( at least of 1.6 ) 👍

**Pull request merged**
