### PR TITLE
[SW-775] Fix link to updated location of development documentation

### PR DESCRIPTION
**Pull request by angela0xdata**

### CODE REVIEW

**Comment by jakubhava** [comment]
Instead of pointing to sources, I would Point the link to the latest generated documentation. In case if master - to latest nightly, in case of rel branch, to latest version of doc for this release.

I can have a look on it, thanks!

**Comment by jakubhava** [comment]
So, for 
master -> https://s3.amazonaws.com/h2o-release/sparkling-water/master/latest.html
rel-2.3 -> http://docs.h2o.ai/sparkling-water/2.3/latest-stable/doc/index.html
rel-2.2 -> http://docs.h2o.ai/sparkling-water/2.2/latest-stable/doc/index.html
rel-2.1 -> http://docs.h2o.ai/sparkling-water/2.1/latest-stable/doc/index.html
rel-2.0 -> http://docs.h2o.ai/sparkling-water/2.0/latest-stable/doc/index.html

@angela0xdata Could you please create pull requests with changes with these links?

**Comment by jakubhava** [comment]
Also as a side-note -> it would be good to go over all links to SW documentation here http://docs.h2o.ai/h2o/latest-stable/index.html and ensure we point to the newly generated documentation. Right now some don't work, some still point to the sources

**Comment by angela0xdata** [comment]
>>>It would be good to go over all links to SW documentation here http://docs.h2o.ai/h2o/latest-stable/index.html 
That link does not point to the current doc site. (Notice that it is missing the Sparkling Water User Guide.) Let me look into why the download site points to an older version of the docs site.

**Comment by jakubhava** [comment]
@angela0xdata oki, I didn't know that http://docs.h2o.ai/h2o/latest-stable/index.html is not the major documentation dispatch page. Either way, it is still online and some people may use it to access Sparkling Water docs. Would be good to make it work anyway. What do you think?

But let's mainly focus on the links update up there in this PR. Could you please do the PRs? That would help a lot!

**Comment by angela0xdata** [comment]
Yes, I was working on this when I noticed the bad link issue (that you pointed out), and I just fixed that for the h2o-3 nightly build. Will finish this issue today.

**Comment by jakubhava** [comment]
perfect, thanks a ton @angela0xdata!

**Comment by jakubhava** [comment]
Feel free to merge whenever you want

**Pull request merged**
