### PR TITLE
[SW-2256] Put generated code into gitignore

### PR DESCRIPTION
**Pull request by jakubhava**

### CODE REVIEW

**Comment by jakubhava** [comment]
@mn-mikke failed on unrelated R intermittent tests ( I wish we could fix that, still no idea), otherwise green

**Comment by mn-mikke** [comment]
On the other hand, what you think about ignoring all src-gen folder in the main `.gitignore`?

**Comment by jakubhava** [comment]
You mean globally? In case other submodule has src-gen folder so it is ignored as well?

I would to manually per submodule

**Comment by mn-mikke** [comment]
ok, no problem.

**Pull request merged**
