### PR TITLE
SW-1415: Docs TOC: Move "Using RSparking" topic into the RSparkling c…

### PR DESCRIPTION
**Pull request by zainhaq-h2o**
Heading levels have been changed in order to move the "Using RSparkling" topic in the SW user guide into the RSparkling chapter.

https://0xdata.atlassian.net/browse/SW-1415

### CODE REVIEW

**Comment by jakubhava** [comment]
I don't understand the context of this change. Rsparkling README is already part of the Sparkling Water documentation

**Comment by zainhaq-h2o** [comment]
> I don't understand the context of this change. Rsparkling README is already part of the Sparkling Water documentation

We just want to streamline the TOC further by consolidating all the RSparkling related documentation under one section.

**Comment by jakubhava** [comment]
Can you pls show the screen before & after the change? Thanks!

**Comment by jakubhava** [comment]
@angela0xdata explain the context for me, thanks!

**Comment by zainhaq-h2o** [comment]
Before:
Screen Shot 2019-07-08 at 11 29 24 AM

After:
Screen Shot 2019-07-08 at 9 44 03 AM

**Comment by jakubhava** [comment]
makes great sense, thank you Zac ! 👍

**Pull request merged**
